"""Synthetic-view tests for the mono calibration core.

Views are generated by projecting the board's known 3D chessboard corners
through a KNOWN ground-truth (K, D) at varied poses — no rendered images
needed, so the math is tested in isolation and without hardware.
"""
from __future__ import annotations

import cv2
import numpy as np
import pytest

from stereo_depth.adapters.calibration.charuco_calibrator import make_charuco_board
from stereo_depth.adapters.calibration.mono_calibrator import (
    coeff_sane,
    estimate_hfov_deg,
    fit_fisheye,
    fit_pinhole,
    holdout_rpe,
    match_object_points,
    select_model,
    split_train_holdout,
    undistort_monotonic,
)

BOARD_ARGS = dict(
    squares_x=7, squares_y=5,
    square_length=0.03, marker_length=0.022,
    dict_name="DICT_5X5_100",
)

IMG_SIZE = (1280, 720)

K_PINHOLE = np.array([[620.0, 0.0, 645.0],
                      [0.0, 618.0, 355.0],
                      [0.0, 0.0, 1.0]])
D_PINHOLE = np.array([-0.18, 0.04, 0.0008, -0.0006, -0.002])

# Radial polynomial that turns over at ~87% of the corner radius: it cannot
# image its own corners, so it must be rejected as fold-back.
D_FOLDBACK = np.array([-0.28, 0.09, 0.0012, -0.0008, -0.014])

# ~145 deg HFOV — wide, but within the <180 deg range cv2.fisheye's atan(r)
# formulation can actually represent.
K_FISHEYE = np.array([[470.0, 0.0, 641.0],
                      [0.0, 469.0, 359.0],
                      [0.0, 0.0, 1.0]])
D_FISHEYE = np.array([0.06, -0.012, 0.004, -0.0006])


# ---------------------------------------------------------------------------
# Synthetic view generation
# ---------------------------------------------------------------------------

def _board():
    return make_charuco_board(**BOARD_ARGS)


def _project(model, obj_xyz, rvec, tvec, K, D):
    if model == "fisheye":
        pts, _ = cv2.fisheye.projectPoints(
            obj_xyz.reshape(1, -1, 3).astype(np.float64), rvec, tvec, K, D.reshape(4, 1)
        )
        return pts.reshape(-1, 2)
    pts, _ = cv2.projectPoints(obj_xyz.astype(np.float64), rvec, tvec, K, D)
    return pts.reshape(-1, 2)


def _rot_bringing_z_to(d):
    """Rotation taking the board normal (0,0,1) onto the unit vector d."""
    a = np.array([0.0, 0.0, 1.0])
    v = np.cross(a, d)
    c = float(np.dot(a, d))
    s = float(np.linalg.norm(v))
    if s < 1e-9:
        return np.eye(3) if c > 0 else np.diag([1.0, -1.0, -1.0])
    vx = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
    return np.eye(3) + vx + vx @ vx * ((1 - c) / (s**2))


def synth_views(
    K_true, D_true, model, *, n=28, seed=0, noise_px=0.0, board=None,
    max_angle_deg=None,
):
    """Return (corners_list, ids_list) of synthetic ChArUco detections.

    Board placements are parameterised by RAY ANGLE from the optical axis,
    not by normalized image coordinates: on a wide-angle lens a normalized
    offset of 0.3 is still near the image centre, and views clustered there
    cannot distinguish one distortion model from another.
    """
    if board is None:
        board, _dict = _board()
    if max_angle_deg is None:
        max_angle_deg = 78.0 if model == "fisheye" else 52.0
    obj_all = np.asarray(board.getChessboardCorners(), dtype=np.float64)  # (24,3)
    center = obj_all.mean(axis=0)
    w, h = IMG_SIZE
    rng = np.random.default_rng(seed)

    # tilt bins: frontal, left, right, up, down — required to make fx/fy and
    # the distortion coefficients separately identifiable
    tilt_specs = [
        (np.array([0.0, 0.0, 1.0]), 0.0),
        (np.array([0.0, 1.0, 0.0]), +25.0),
        (np.array([0.0, 1.0, 0.0]), -25.0),
        (np.array([1.0, 0.0, 0.0]), +25.0),
        (np.array([1.0, 0.0, 0.0]), -25.0),
    ]
    # centre plus two rings of ray directions -> coverage out to the corners
    placements = [(0.0, 0.0)]
    for frac in (0.45, 0.85):
        for phi in range(0, 360, 45):
            placements.append((frac * max_angle_deg, float(phi)))

    corners_list: list[np.ndarray] = []
    ids_list: list[np.ndarray] = []

    for i in range(n):
        axis, deg = tilt_specs[i % len(tilt_specs)]
        rvec_tilt = axis * np.deg2rad(deg) + rng.normal(0.0, 0.06, 3)
        R_tilt, _ = cv2.Rodrigues(rvec_tilt.reshape(3, 1))

        theta_deg, phi_deg = placements[i % len(placements)]
        theta = np.deg2rad(theta_deg + rng.normal(0.0, 2.0))
        phi = np.deg2rad(phi_deg + rng.normal(0.0, 6.0))
        d = np.array([np.sin(theta) * np.cos(phi),
                      np.sin(theta) * np.sin(phi),
                      np.cos(theta)])

        # face the board back toward the camera, then apply the tilt
        R = _rot_bringing_z_to(-d) @ R_tilt
        rvec = cv2.Rodrigues(R)[0]

        dist = float(rng.uniform(0.40, 0.70))
        target = (dist * d).reshape(3, 1)
        tvec = target - R @ center.reshape(3, 1)

        pts = _project(model, obj_all, rvec, tvec, K_true, D_true)
        if noise_px > 0:
            pts = pts + rng.normal(0.0, noise_px, pts.shape)

        inside = (pts[:, 0] >= 0) & (pts[:, 0] < w) & (pts[:, 1] >= 0) & (pts[:, 1] < h)
        if inside.sum() < 8:
            continue
        ids = np.nonzero(inside)[0].astype(np.int32).reshape(-1, 1)
        corners_list.append(pts[inside].astype(np.float32).reshape(-1, 1, 2))
        ids_list.append(ids)

    return corners_list, ids_list


def _fit_all(corners, ids, board):
    return {
        "pinhole": fit_pinhole(corners, ids, board, IMG_SIZE),
        "rational": fit_pinhole(corners, ids, board, IMG_SIZE, rational=True),
        "fisheye": fit_fisheye(corners, ids, board, IMG_SIZE),
    }


def _select(corners, ids, board, *, holdout_frac=0.3, seed=0):
    """Full split -> fit -> evaluate -> select, as run_calibrate_mono does."""
    train_idx, hold_idx = split_train_holdout(
        len(corners), holdout_frac=holdout_frac, seed=seed, min_train=12
    )
    tc = [corners[i] for i in train_idx]
    ti = [ids[i] for i in train_idx]
    fits = _fit_all(tc, ti, board)

    hold_obj, hold_img = [], []
    if hold_idx:
        hc = [corners[i] for i in hold_idx]
        hi = [ids[i] for i in hold_idx]
        hold_obj, hold_img, _ = match_object_points(hc, hi, board)

    scores, hfovs, sanity, mono = {}, {}, {}, {}
    for m, f in fits.items():
        scores[m] = holdout_rpe(f, hold_obj, hold_img) if hold_obj else float("nan")
        if f.ok:
            hfovs[m] = estimate_hfov_deg(f.K, f.D, IMG_SIZE, m)
            sanity[m] = coeff_sane(f, IMG_SIZE)
            mono[m] = undistort_monotonic(f.K, f.D, IMG_SIZE, m)
        else:
            hfovs[m] = float("nan")
            sanity[m] = (False, ["fit failed"])
            mono[m] = False

    return select_model(fits, scores, hfovs, sanity, mono, has_holdout=bool(hold_obj)), fits


# ---------------------------------------------------------------------------
# Recovery of ground truth
# ---------------------------------------------------------------------------

def test_pinhole_recovers_ground_truth():
    board, _ = _board()
    corners, ids = synth_views(K_PINHOLE, D_PINHOLE, "pinhole", board=board)
    fit = fit_pinhole(corners, ids, board, IMG_SIZE)

    assert fit.ok, fit.error
    assert fit.rms_train < 0.05
    assert fit.K[0, 0] == pytest.approx(K_PINHOLE[0, 0], rel=0.01)
    assert fit.K[1, 1] == pytest.approx(K_PINHOLE[1, 1], rel=0.01)
    assert fit.K[0, 2] == pytest.approx(K_PINHOLE[0, 2], rel=0.01)
    assert fit.K[1, 2] == pytest.approx(K_PINHOLE[1, 2], rel=0.01)
    assert fit.D[0] == pytest.approx(D_PINHOLE[0], abs=0.02)
    assert fit.D[1] == pytest.approx(D_PINHOLE[1], abs=0.02)


def test_fisheye_recovers_ground_truth():
    board, _ = _board()
    corners, ids = synth_views(K_FISHEYE, D_FISHEYE, "fisheye", board=board)
    fit = fit_fisheye(corners, ids, board, IMG_SIZE)

    assert fit.ok, fit.error
    assert fit.rms_train < 0.05
    assert fit.K[0, 0] == pytest.approx(K_FISHEYE[0, 0], rel=0.02)
    assert fit.K[1, 1] == pytest.approx(K_FISHEYE[1, 1], rel=0.02)
    assert fit.K[0, 2] == pytest.approx(K_FISHEYE[0, 2], rel=0.02)
    assert fit.K[1, 2] == pytest.approx(K_FISHEYE[1, 2], rel=0.02)
    assert len(fit.D) == 4


def test_rational_fit_produces_eight_coefficients():
    board, _ = _board()
    corners, ids = synth_views(K_PINHOLE, D_PINHOLE, "pinhole", board=board)
    fit = fit_pinhole(corners, ids, board, IMG_SIZE, rational=True)

    assert fit.ok, fit.error
    assert len(fit.D) == 8
    assert fit.K[0, 0] == pytest.approx(K_PINHOLE[0, 0], rel=0.02)


def test_per_view_rpe_one_entry_per_view():
    board, _ = _board()
    corners, ids = synth_views(K_PINHOLE, D_PINHOLE, "pinhole", board=board)
    fit = fit_pinhole(corners, ids, board, IMG_SIZE)

    assert len(fit.per_view_rpe) == fit.n_views
    assert all(np.isfinite(r) for r in fit.per_view_rpe)


# ---------------------------------------------------------------------------
# Selection fairness — the anti-overfitting guarantee
# ---------------------------------------------------------------------------

def test_pinhole_data_selects_pinhole_despite_noise():
    """With realistic pixel noise, rational fits train better but must NOT
    be selected — holdout RPE plus the complexity margin protect us."""
    board, _ = _board()
    corners, ids = synth_views(
        K_PINHOLE, D_PINHOLE, "pinhole", n=32, seed=3, noise_px=0.15, board=board
    )
    sel, fits = _select(corners, ids, board)

    assert sel.selected == "pinhole", sel.reason
    # sanity: the more complex model really did fit the training set at least
    # as well — proving the margin (not raw train error) drove the decision
    assert fits["rational"].ok
    assert fits["rational"].rms_train <= fits["pinhole"].rms_train + 1e-6


def test_fisheye_data_selects_fisheye():
    board, _ = _board()
    corners, ids = synth_views(
        K_FISHEYE, D_FISHEYE, "fisheye", n=32, seed=5, noise_px=0.1, board=board
    )
    sel, _fits = _select(corners, ids, board)

    assert sel.selected == "fisheye", sel.reason


def test_selection_table_reports_every_model():
    board, _ = _board()
    corners, ids = synth_views(K_PINHOLE, D_PINHOLE, "pinhole", n=30, seed=1, board=board)
    sel, _ = _select(corners, ids, board)

    assert set(sel.table) == {"pinhole", "rational", "fisheye"}
    for entry in sel.table.values():
        assert "ok" in entry and "disqualified" in entry
    assert sel.reason


def test_select_model_prefers_simpler_on_a_tie():
    """Equal holdout scores -> the simplest qualifying model wins."""
    fits = {
        m: fit for m, fit in (
            (m, _stub_fit(m)) for m in ("pinhole", "rational", "fisheye")
        )
    }
    scores = {"pinhole": 0.30, "rational": 0.30, "fisheye": 0.30}
    hfovs = {m: 90.0 for m in scores}
    sanity = {m: (True, []) for m in scores}
    mono = {m: True for m in scores}

    sel = select_model(fits, scores, hfovs, sanity, mono)
    assert sel.selected == "pinhole"


def test_select_model_upgrades_when_margin_is_cleared():
    fits = {m: _stub_fit(m) for m in ("pinhole", "rational", "fisheye")}
    # fisheye is dramatically better -> clears both margins
    scores = {"pinhole": 2.00, "rational": 1.90, "fisheye": 0.20}
    hfovs = {m: 120.0 for m in scores}
    sanity = {m: (True, []) for m in scores}
    mono = {m: True for m in scores}

    sel = select_model(fits, scores, hfovs, sanity, mono)
    assert sel.selected == "fisheye"


def test_select_model_disqualifies_non_monotonic_model():
    fits = {m: _stub_fit(m) for m in ("pinhole", "rational", "fisheye")}
    scores = {"pinhole": 1.00, "rational": 0.10, "fisheye": 1.00}
    hfovs = {m: 90.0 for m in scores}
    sanity = {m: (True, []) for m in scores}
    mono = {"pinhole": True, "rational": False, "fisheye": True}   # rational folds back

    sel = select_model(fits, scores, hfovs, sanity, mono)
    assert sel.selected != "rational"
    assert sel.table["rational"]["disqualified"]


def _stub_fit(model: str):
    from stereo_depth.adapters.calibration.mono_calibrator import MonoModelFit
    n_d = {"pinhole": 5, "rational": 8, "fisheye": 4}[model]
    return MonoModelFit(
        model, True,
        K=np.array([[600.0, 0, 640.0], [0, 600.0, 360.0], [0, 0, 1.0]]),
        D=np.zeros(n_d), rms_train=0.3, n_views=20,
    )


# ---------------------------------------------------------------------------
# Sanity checks
# ---------------------------------------------------------------------------

def test_undistort_monotonic_accepts_reasonable_distortion():
    assert undistort_monotonic(K_PINHOLE, D_PINHOLE, IMG_SIZE, "pinhole")
    assert undistort_monotonic(K_FISHEYE, D_FISHEYE, IMG_SIZE, "fisheye")


def test_undistort_monotonic_rejects_foldback():
    """A radial polynomial that turns over inside the image is rejected —
    it cannot image its own corners, so its undistort map would be garbage."""
    assert not undistort_monotonic(K_PINHOLE, D_FOLDBACK, IMG_SIZE, "pinhole")


def test_coeff_sane_flags_rational_denominator_pole():
    fit = _stub_fit("rational")
    fit.D = np.array([0.1, 0.0, 0.0, 0.0, 0.0, -5.0, 0.0, 0.0])   # k4 = -5 -> pole
    ok, problems = coeff_sane(fit, IMG_SIZE)

    assert not ok
    assert any("pole" in p for p in problems)


def test_coeff_sane_flags_focal_asymmetry():
    fit = _stub_fit("pinhole")
    fit.K = np.array([[600.0, 0, 640.0], [0, 900.0, 360.0], [0, 0, 1.0]])
    ok, problems = coeff_sane(fit, IMG_SIZE)

    assert not ok
    assert any("fx/fy" in p for p in problems)


def test_coeff_sane_flags_off_center_principal_point():
    fit = _stub_fit("pinhole")
    fit.K = np.array([[600.0, 0, 100.0], [0, 600.0, 360.0], [0, 0, 1.0]])
    ok, problems = coeff_sane(fit, IMG_SIZE)

    assert not ok
    assert any("principal point" in p for p in problems)


def test_estimate_hfov_is_wider_for_fisheye():
    hfov_pin = estimate_hfov_deg(K_PINHOLE, D_PINHOLE, IMG_SIZE, "pinhole")
    hfov_fish = estimate_hfov_deg(K_FISHEYE, D_FISHEYE, IMG_SIZE, "fisheye")

    assert 60.0 < hfov_pin < 130.0
    assert hfov_fish > hfov_pin


# ---------------------------------------------------------------------------
# Holdout split
# ---------------------------------------------------------------------------

def test_split_is_deterministic_for_a_seed():
    a = split_train_holdout(40, holdout_frac=0.25, seed=7)
    b = split_train_holdout(40, holdout_frac=0.25, seed=7)
    c = split_train_holdout(40, holdout_frac=0.25, seed=8)

    assert a == b
    assert a != c


def test_split_partitions_all_views_without_overlap():
    train, hold = split_train_holdout(40, holdout_frac=0.25, seed=0)

    assert len(hold) == 10
    assert len(train) == 30
    assert set(train).isdisjoint(hold)
    assert set(train) | set(hold) == set(range(40))


def test_split_yields_no_holdout_when_views_are_scarce():
    train, hold = split_train_holdout(13, holdout_frac=0.25, seed=0, min_train=12)

    assert len(hold) <= 1
    assert len(train) >= 12
